onlinemovie/movie/urls.py
from django.contrib import admin
from django.urls import path
from movie import views

app_name="movie"

urlpatterns = [
    path('',views.home,name="home"),
    path('add/',views.addmovie,name="addmovie"),
    path('details/<int:n>/',views.details,name="details"),
    path('update/<int:n>/',views.Movieupdate,name="update"),
    path('delete/<int:n>/',views.Moviedelete,name="delete")
]

onlinemovie/onlinemovie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinemovie/movie/models.py
from django.db import models

class Movie(models.Model):
    name=models.CharField(max_length=30)
    desc=models.TextField()
    year=models.IntegerField()
    language=models.CharField(max_length=30)
    pic=models.ImageField(upload_to='picture',null=True,blank=True)

    def __str__(self):
        return self.name

onlinemovie/movie/forms.py
from django import forms
from movie.models import Movie

class Add(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'

onlinemovie/movie/views.py
from django.shortcuts import render
from movie.models import Movie
from movie.forms import Add

def home(request):

    m=Movie.objects.all()
    return render(request,'home.html',{'m':m})

def addmovie(request):

    if(request.method=="POST"):
        f=Add(request.POST,request.FILES)
        if f.is_valid():
            f.save()
            return home(request)

    f=Add()
    return render(request,'addmovie.html',{'f':f})

def details(request,n):

    d=Movie.objects.get(id=n)
    return render(request,'details.html',{'d':d})

def Movieupdate(request,n):
    ed=Movie.objects.get(id=n)
    if(request.method=="POST"):
        f=Add(request.POST,request.FILES,instance=ed)
        if f.is_valid():
            f.save()
            return home(request)


    f=Add(instance=ed)
    return render(request,'addmovie.html',{'f':f})

def Moviedelete(request,n):
    dlt=Movie.objects.get(id=n)
    dlt.delete()

    return home(request)

onlinemovie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movie</title>
</head>
<body>
{% block content %}
<h3> Add Movie </h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{f.as_table}}
</table>
<input type="submit">

{% endblock %}
</body>
</html>

onlinemovie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movie Center</a>
    <form class="d-flex">
      <a href="{% url 'movie:addmovie' %}" class="btn btn-outline-success text-light btn-outline-light link-success" type="submit">Add Movie</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

onlinemovie/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
{% block content %}
<div class="container-fluid">
  <div class="row mt-5">
    <div class="col-12 col-lg-2" style="width:800px;">
        <div class="card mb-3 ms-5" style="max-width: 800px;">
            <img src="{{d.pic.url}}" class="card-img-top mt-5" alt="..." style="width:700px">
                <div class="card-body">
                <h5 class="card-title">{{d.name}}</h5>
                <p class="card-text">{{d.desc}}</p>
                    <h5 class="card-text">Year of Release: {{d.year}}</h5>
                    <h5 class="card-text">Released Language:{{d.language}}</h5>
                    <a href="{% url 'movie:update' d.id %}" class="btn btn-success"> Update </a>
                    <a href="{% url 'movie:delete' d.id %}" class="btn btn-success"> Delete </a>
                </div>
        </div>
    </div>

  </div>
</div>

{% endblock %}

</body>
</html>

onlinemovie/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
{% block content %}
<h3 class="head mt-5 ms-5"> Movies </h3>
<div class="container-fluid">
<div class="row mt-5 mb-5">
{% for i in m %}
<div class="col-3">
<div class="card-group">
  <div class="card">
    <img src="{{i.pic.url}}" class="card-img-top" alt="..." style="height:250px;">
    <div class="card-body" style="width:35 rem;">
      <h5 class="card-title">{{i.name}}</h5>
        <h5 class="card-text">Year of Release: {{i.year}}</h5>
        <h5 class="card-text">Released Language:{{i.language}}</h5>
        <a href="{% url 'movie:details' i.id %}" class="btn btn-primary">More Details</a>
    </div>
  </div>
</div>
</div>
    {% endfor %}
</div>
</div>

{% endblock %}

</body>
</html>